-- Creating Data Warehouse 
-- CREATE WAREHOUSE MARKETING_CAMP_WH
-- WITH
-- WAREHOUSE_SIZE = "XSMALL"
-- AUTO_SUSPEND = 60
-- AUTO_RESUME = TRUE;

-- CREATE DATABASE MARKEITING_CAMP_ANALYSIS

-- CREATE SCHEMA RAW_DATA

-- CREATE SCHEMA CLEAN_DATA

SHOW SCHEMAS;
SELECT CURRENT_USER(), CURRENT_ROLE();

SELECT * FROM RAW_DATA.CUSTOMERS

USE SCHEMA RAW_DATA;

-- ==============================================================================
-- STREAMS
-- ==============================================================================
-- -- CUSTOMERS
-- CREATE STREAM CUSTOMERS_STREAM
-- ON TABLE RAW_DATA.CUSTOMERS;

-- -- CUSTOMERS JOURNEY
-- CREATE STREAM CUSTOMER_JOURNEY_STREAM
-- ON TABLE RAW_DATA.CUSTOMER_JOURNEY

-- -- CUSTOMER REVIEW
-- CREATE STREAM CUSTOMER_REVIEW_STREAM
-- ON TABLE RAW_DATA.CUSTOMER_REVIEWS

-- -- CUSTOMER ENGAGEMENT
-- CREATE STREAM CUSTOMER_ENGAGEMENT_STREAM
-- ON TABLE RAW_DATA.CUSTOMERS_ENGAGEMENT

-- -- PRODUCTS
-- CREATE STREAM PRODUCTS_STREAM
-- ON TABLE RAW_DATA.PRODUCTS

-- -- GEOGRAPHY
-- CREATE STREAM GEOGRAPHY_STREAM
-- ON TABLE RAW_DATA.GEOGRAPHY

SHOW STREAMS
-- ========================================================================================================================================================
-- EDA
-- ========================================================================================================================================================
-- CUSTOMERS EDA
DESC TABLE CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL OR EMAIL IS NULL;
SELECT CUSTOMER_ID, COUNT(*) FROM CUSTOMERS GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1;
SELECT MIN(AGE), MAX(AGE) FROM CUSTOMERS;
-- --------------------------------------------------------------------------------------------------------------------------------------------------------
-- CUSTOMER_JOURNEY EDA
DESC TABLE CUSTOMER_JOURNEY;
SELECT * FROM CUSTOMER_JOURNEY WHERE JOURNEYID IS NULL OR CUSTOMERID IS NULL OR PRODUCTID IS NULL;

-- IMPORTANT POINT 
-- OrderID, CustomerID,ProductID
-- Customer can bought twice
-- So as per this we can find duplicates with the OrderID becuase CustomerID and ProductID can be the same.

-- But OrderID and CustomerID can be the same but ProductID can be different because, same customer in one order can buy multiple products.
-- So sometimes finding duplicates using only OrderID can also make mistakes, thats why we group it by CustomerID, ProductID and OrderID.
-- ALL DUPLICATES
WITH DuplicateRecords AS
(SELECT JourneyID, CustomerID, ProductID, VisitDate, Stage, Action, Duration,
ROW_NUMBER() OVER(PARTITION BY CustomerID, ProductID, VisitDate, Stage, Action ORDER BY JourneyID) AS Row_Num
FROM customer_journey)
SELECT * FROM DuplicateRecords WHERE Row_Num > 1 ORDER BY JourneyID;

SELECT MIN(VISITDATE), MAX(VISITDATE) FROM CUSTOMER_JOURNEY;
SELECT ACTION, COUNT(ACTION) FROM CUSTOMER_JOURNEY GROUP BY ACTION ORDER BY COUNT(ACTION);
SELECT STAGE, COUNT(STAGE) FROM CUSTOMER_JOURNEY GROUP BY STAGE ORDER BY COUNT(STAGE);

SELECT MIN(DURATION), MAX(DURATION) FROM CUSTOMER_JOURNEY;

-- FINAL CLEAN JOURNEY TABLE
WITH CTE1 AS
(SELECT JOURNEYID, CUSTOMERID, PRODUCTID, VISITDATE, UPPER(STAGE) AS STAGE, ACTION, DURATION,
AVG(TRY_TO_NUMBER(DURATION)) OVER(PARTITION BY VISITDATE) AS AVG_DURATION,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID, PRODUCTID, VISITDATE, UPPER(STAGE), ACTION ORDER BY JOURNEYID) AS ROW_NUM
FROM CUSTOMER_JOURNEY)
SELECT JOURNEYID, CUSTOMERID, PRODUCTID, VISITDATE, STAGE, ACTION, COALESCE(TRY_TO_NUMBER(DURATION), AVG_DURATION) AS DURATION, ROW_NUM
FROM CTE1 WHERE ROW_NUM = 1;
-- --------------------------------------------------------------------------------------------------------------------------------------------------------
-- CUSTOMER_REVIEWS EDA
DESC TABLE CUSTOMER_REVIEWS;
SELECT * FROM CUSTOMER_REVIEWS LIMIT 5;
SELECT * FROM CUSTOMER_REVIEWS WHERE REVIEW_ID IS NULL OR CUSTOMER_ID IS NULL OR PRODUCT_ID IS NULL OR REVIEW_DATE IS NULL OR RATING IS NULL OR REVIEW_TEXT IS NULL;
SELECT MIN(REVIEW_DATE), MAX(REVIEW_DATE) FROM CUSTOMER_REVIEWS;
SELECT MIN(RATING), MAX(RATING) FROM CUSTOMER_REVIEWS;

SELECT * FROM 
(SELECT *, ROW_NUMBER() OVER(PARTITION BY REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_DATE, RATING, REVIEW_TEXT ORDER BY REVIEW_ID) AS ROW_NUM FROM CUSTOMER_REVIEWS)
WHERE ROW_NUM = 1;
-- --------------------------------------------------------------------------------------------------------------------------------------------------------
-- Customer_Engagement EDA
DESC TABLE CUSTOMERS_ENGAGEMENT;
SELECT * FROM CUSTOMERS_ENGAGEMENT LIMIT 5;
SELECT COUNT(*) FROM CUSTOMERS_ENGAGEMENT;

SELECT ENGAGEMENT_ID, COUNT(*) FROM CUSTOMERS_ENGAGEMENT GROUP BY ENGAGEMENT_ID HAVING COUNT(*) > 1;
SELECT * FROM CUSTOMERS_ENGAGEMENT WHERE ENGAGEMENT_ID IS NULL OR CONTENT_TYPE IS NULL OR LIKES IS NULL OR ENGAGEMENT_DATE IS NULL OR PRODUCT_ID IS NULL OR VIEWS_CLICKS IS NULL;
SELECT MIN(ENGAGEMENT_DATE), MAX(ENGAGEMENT_DATE) FROM CUSTOMERS_ENGAGEMENT;
SELECT CONTENT_TYPE, COUNT(CONTENT_TYPE) FROM CUSTOMERS_ENGAGEMENT GROUP BY CONTENT_TYPE ORDER BY COUNT(CONTENT_TYPE);

-- Clean and Normalize the Engagement Data Table

SELECT ENGAGEMENT_ID, CONTENT_ID, CAMPAIGN_ID, PRODUCT_ID,
       REPLACE(UPPER(CONTENT_TYPE),'SOCIALMEDIA', 'SOCIAL MEDIA') AS CONTENT_TYPE,
       TRY_TO_NUMBER(LEFT(VIEWS_CLICKS, CHARINDEX('-', VIEWS_CLICKS) -1 )) AS VIEWS,
       TRY_TO_NUMBER(RIGHT(VIEWS_CLICKS, LEN(VIEWS_CLICKS) - CHARINDEX('-', VIEWS_CLICKS))) AS CLICKS,
       LIKES, ENGAGEMENT_DATE
FROM CUSTOMERS_ENGAGEMENT
WHERE UPPER(TRIM(CONTENT_TYPE)) <> 'NEWSLETTER';
-- --------------------------------------------------------------------------------------------------------------------------------------------------------
-- Geography EDA
DESC TABLE GEOGRAPHY;
SELECT * FROM GEOGRAPHY;
-- --------------------------------------------------------------------------------------------------------------------------------------------------------
-- Products EDA
DESC TABLE PRODUCTS;
SELECT * FROM PRODUCTS;

SELECT *,
     CASE
      WHEN price < 50 THEN 'Low'
      WHEN price BETWEEN 50 AND 200 THEN 'Medium'
      WHEN price > 200 THEN 'High'
      END AS price_category
FROM products;

-- ========================================================================================================================================================
-- TABLE CREATION IN CLEAN_DATA SCHEMA
-- ========================================================================================================================================================
-- -- CUSTOMER_JOURNEY CLEAN TABLE
-- CREATE TABLE CLEAN_DATA.CUSTOMER_JOURNEY
-- (
--     JOURNEYID   NUMBER(38,0),
--     CUSTOMERID  NUMBER(38,0),
--     PRODUCTID   NUMBER(38,0),
--     VISITDATE   DATE,
--     STAGE       VARCHAR,
--     ACTION      VARCHAR,
--     DURATION    NUMBER(38,2)
-- );

-- INSERT INTO CLEAN_DATA.CUSTOMER_JOURNEY
-- (JOURNEYID, CUSTOMERID, PRODUCTID, VISITDATE, STAGE, ACTION, DURATION)
-- WITH CTE AS
-- (SELECT JOURNEYID, CUSTOMERID, PRODUCTID, VISITDATE,
--         UPPER(TRIM(STAGE)) AS STAGE,
--         TRIM(ACTION) AS ACTION,
--         DURATION,
--         AVG(TRY_TO_NUMBER(DURATION)) OVER (PARTITION BY VISITDATE) AS AVG_DURATION,
--         ROW_NUMBER() OVER( PARTITION BY CUSTOMERID, PRODUCTID, VISITDATE, UPPER(TRIM(STAGE)), TRIM(ACTION) ORDER BY JOURNEYID) AS ROW_NUM
-- FROM RAW_DATA.CUSTOMER_JOURNEY)
-- SELECT
--     JOURNEYID,
--     CUSTOMERID,
--     PRODUCTID,
--     VISITDATE,
--     STAGE,
--     ACTION,
--     COALESCE(
--         TRY_TO_NUMBER(DURATION),
--         AVG_DURATION
--     ) AS DURATION
-- FROM CTE WHERE ROW_NUM = 1;
SELECT * FROM CLEAN_DATA.CUSTOMER_JOURNEY LIMIT 5;
DESC TABLE CLEAN_DATA.CUSTOMER_JOURNEY;

-- ========================================================================================================================================================
-- TASK : CUSTOMER_JOURNEY
-- ========================================================================================================================================================
USE SCHEMA CLEAN_DATA;

SELECT * FROM RAW_DATA.CUSTOMER_JOURNEY LIMIT 5;

-- CREATE OR REPLACE TASK CLEAN_DATA.CUSTOMER_JOURNEY_TASK
-- WAREHOUSE = MARKETING_CAMP_WH
-- SCHEDULE = '1 MINUTE'
-- WHEN SYSTEM$STREAM_HAS_DATA('RAW_DATA.CUSTOMER_JOURNEY_STREAM')
-- AS
-- MERGE INTO CLEAN_DATA.CUSTOMER_JOURNEY AS TARGET
-- USING
-- (
--     WITH STREAM_DATA AS
--     (   SELECT
--             JOURNEYID,
--             CUSTOMERID,
--             PRODUCTID,
--             VISITDATE,
--             UPPER(TRIM(STAGE)) AS STAGE,
--             TRIM(ACTION) AS ACTION,
--             DURATION,
--             METADATA$ACTION,
--             METADATA$ISUPDATE
--         FROM RAW_DATA.CUSTOMER_JOURNEY_STREAM
--         WHERE METADATA$ACTION = 'INSERT'
--     ),
--     DEDUPLICATED AS
--     (   SELECT
--             JOURNEYID,
--             CUSTOMERID,
--             PRODUCTID,
--             VISITDATE,
--             STAGE,
--             ACTION,
--             DURATION,
--             ROW_NUMBER() OVER(PARTITION BY CUSTOMERID, PRODUCTID, VISITDATE, STAGE, ACTION ORDER BY JOURNEYID) AS ROW_NUM
--         FROM STREAM_DATA
--     ),
--     AVG_DURATION AS
--     (   SELECT
--             VISITDATE,
--             AVG(DURATION) AS AVG_DURATION
--         FROM CLEAN_DATA.CUSTOMER_JOURNEY
--         GROUP BY VISITDATE
--     )
--     SELECT
--         D.JOURNEYID,
--         D.CUSTOMERID,
--         D.PRODUCTID,
--         D.VISITDATE,
--         D.STAGE,
--         D.ACTION,
--         COALESCE(
--             TRY_TO_NUMBER(NULLIF(TRIM(D.DURATION), 'NULL')),
--             A.AVG_DURATION
--         ) AS DURATION
--     FROM DEDUPLICATED D
--     LEFT JOIN AVG_DURATION A ON D.VISITDATE = A.VISITDATE
--     WHERE D.ROW_NUM = 1
-- ) AS SOURCE
-- ON TARGET.JOURNEYID = SOURCE.JOURNEYID
-- WHEN MATCHED THEN
--     UPDATE SET
--         TARGET.CUSTOMERID = SOURCE.CUSTOMERID,
--         TARGET.PRODUCTID = SOURCE.PRODUCTID,
--         TARGET.VISITDATE = SOURCE.VISITDATE,
--         TARGET.STAGE = SOURCE.STAGE,
--         TARGET.ACTION = SOURCE.ACTION,
--         TARGET.DURATION = SOURCE.DURATION
-- WHEN NOT MATCHED THEN
--     INSERT
--     (
--         JOURNEYID,
--         CUSTOMERID,
--         PRODUCTID,
--         VISITDATE,
--         STAGE,
--         ACTION,
--         DURATION
--     )
--     VALUES
--     (
--         SOURCE.JOURNEYID,
--         SOURCE.CUSTOMERID,
--         SOURCE.PRODUCTID,
--         SOURCE.VISITDATE,
--         SOURCE.STAGE,
--         SOURCE.ACTION,
--         SOURCE.DURATION
--     );

SHOW TASKS IN SCHEMA CLEAN_DATA; 
ALTER TASK CLEAN_DATA.CUSTOMER_JOURNEY_TASK RESUME;

SELECT * FROM RAW_DATA.CUSTOMER_JOURNEY_STREAM;

SELECT COUNT(*) FROM CLEAN_DATA.CUSTOMER_JOURNEY;

-- INSERT INTO RAW_DATA.CUSTOMER_JOURNEY
-- (
--     JOURNEYID,
--     CUSTOMERID,
--     PRODUCTID,
--     VISITDATE,
--     STAGE,
--     ACTION,
--     DURATION
-- )
-- VALUES
-- (
--     3934,
--     64,
--     18,
--     '2026-09-11',
--     'Checkout',
--     'Test-Insert',
--     '100'
-- );

SELECT MAX(JOURNEYID) AS MAX_JOURNEYID
FROM CLEAN_DATA.CUSTOMER_JOURNEY; 
 
-- EXECUTE TASK CLEAN_DATA.CUSTOMER_JOURNEY_TASK;

-- ========================================================================================================================================================
-- TASK : CUSTOMERS
-- ========================================================================================================================================================
-- CREATE OR REPLACE TABLE CLEAN_DATA.CUSTOMERS AS
-- SELECT *
-- FROM RAW_DATA.CUSTOMERS;

SELECT * FROM CLEAN_DATA.CUSTOMERS LIMIT 5;

-- CREATE OR REPLACE TASK CLEAN_DATA.CUSTOMERS_TASK
-- WAREHOUSE = MARKETING_CAMP_WH
-- SCHEDULE = '1 MINUTE'
-- WHEN
-- SYSTEM$STREAM_HAS_DATA('RAW_DATA.CUSTOMERS_STREAM')
-- AS
-- MERGE INTO CLEAN_DATA.CUSTOMERS AS TARGET
-- USING
-- (SELECT CUSTOMER_ID, CUSTOMER_NAME, EMAIL, GENDER, AGE, GEOGRAPHY_ID
-- FROM RAW_DATA.CUSTOMERS_STREAM WHERE METADATA$ACTION = 'INSERT') AS SOURCE
-- ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
-- WHEN MATCHED THEN
--   UPDATE ALL BY NAME   -- NAME = all column names
-- WHEN NOT MATCHED THEN
--   INSERT ALL BY NAME;  -- NAME = all column names

SHOW TASKS IN SCHEMA CLEAN_DATA;
-- ALTER TASK CLEAN_DATA.CUSTOMERS_TASK RESUME;

SELECT count(*) FROM CUSTOMERS;

-- INSERT INTO RAW_DATA.CUSTOMERS
-- (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, GENDER, AGE, GEOGRAPHY_ID)
-- VALUES
-- (9999, 'Test Customer', 'test9999@example.com', 'Male', 30, 2);

SELECT * FROM RAW_DATA.CUSTOMERS_STREAM;

SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = 9999;

-- EXECUTE TASK CLEAN_DATA.CUSTOMERS_TASK;


-- ========================================================================================================================================================
-- TASK : GEOGRAPHY TASK
-- ========================================================================================================================================================
-- CREATE OR REPLACE TABLE CLEAN_DATA.GEOGRAPHY AS
-- SELECT *
-- FROM RAW_DATA.GEOGRAPHY;
SELECT * FROM CLEAN_DATA.GEOGRAPHY LIMIT 5;

CREATE OR REPLACE TASK CLEAN_DATA.GEOGRAPHY_TASK
WAREHOUSE = MARKETING_CAMP_WH
SCHEDULE = '1 MINUTE'
WHEN
SYSTEM$STREAM_HAS_DATA('RAW_DATA.GEOGRAPHY_STREAM')
AS 
MERGE INTO CLEAN_DATA.GEOGRAPHY AS TARGET
USING
(SELECT GEOGRAPHY_ID, COUNTRY, CITY FROM RAW_DATA.GEOGRAPHY_STREAM WHERE METADATA$ACTION = 'INSERT') AS SOURCE
ON TARGET.GEOGRAPHY_ID = SOURCE.GEOGRAPHY_ID
WHEN MATCHED THEN
    UPDATE ALL BY NAME
WHEN NOT MATCHED THEN
    INSERT ALL BY NAME;

SELECT * FROM GEOGRAPHY;

SHOW TASKS IN SCHEMA CLEAN_DATA;
ALTER TASK CLEAN_DATA.GEOGRAPHY_TASK RESUME;

-- INSERT INTO RAW_DATA.GEOGRAPHY
-- (GEOGRAPHY_ID, COUNTRY, CITY)
-- VALUES
-- (9999, 'INDIA', 'MUMBAI');

SELECT * FROM RAW_DATA.GEOGRAPHY_STREAM;
SELECT * FROM GEOGRAPHY WHERE GEOGRAPHY_ID = 9999;

-- EXECUTE TASK CLEAN_DATA.GEOGRAPHY_TASK;


-- ========================================================================================================================================================
-- TASK : PRODUCT TASK
-- ========================================================================================================================================================
-- CREATE OR REPLACE TABLE CLEAN_DATA.PRODUCTS AS
-- SELECT
--     PRODUCT_ID,
--     PRODUCT_NAME,
--     CATEGORY,
--     PRICE,
--     CASE
--         WHEN PRICE < 50 THEN 'Low'
--         WHEN PRICE BETWEEN 50 AND 200 THEN 'Medium'
--         WHEN PRICE > 200 THEN 'High'
--     END AS PRICE_CATEGORY
-- FROM RAW_DATA.PRODUCTS;

-- CREATE OR REPLACE TASK CLEAN_DATA.PRODUCTS_TASK
-- WAREHOUSE = MARKETING_CAMP_WH
-- SCHEDULE = '1 MINUTE'
-- WHEN
-- SYSTEM$STREAM_HAS_DATA('RAW_DATA.PRODUCTS_STREAM')
-- AS
-- MERGE INTO CLEAN_DATA.PRODUCTS AS TARGET 
-- USING
-- (SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, CATEGORY,
--         CASE
--             WHEN PRICE < 50 THEN 'Low'
--             WHEN PRICE BETWEEN 50 AND 200 THEN 'Medium'
--             WHEN PRICE > 200 THEN 'High'
--         END AS PRICE_CATEGORY
-- FROM RAW_DATA.PRODUCTS_STREAM
-- WHERE METADATA$ACTION = 'INSERT'
-- ) AS SOURCE
-- ON TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID
-- WHEN MATCHED THEN 
--   UPDATE ALL BY NAME
-- WHEN NOT MATCHED THEN
--   INSERT ALL BY NAME;

SHOW TASKS IN SCHEMA CLEAN_DATA;
ALTER TASK CLEAN_DATA.PRODUCTS_TASK RESUME;

SELECT * FROM CLEAN_DATA.PRODUCTS WHERE PRODUCT_ID = 99;

-- INSERT INTO RAW_DATA.PRODUCTS(PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE)
-- VALUES(99, 'Cricket Bat', 'Cricket', 899);

SELECT * FROM RAW_DATA.PRODUCTS_STREAM;

SELECT * FROM RAW_DATA.PRODUCTS;
-- EXECUTE TASK CLEAN_DATA.PRODUCTS_TASK;

-- ========================================================================================================================================================
-- TASK : CUSTOMERS_ENGAGEMENT TASK
-- ========================================================================================================================================================
-- CREATE OR REPLACE TABLE CLEAN_DATA.CUSTOMERS_ENGAGEMENT AS
-- SELECT
--     ENGAGEMENT_ID,
--     CONTENT_ID,
--     CAMPAIGN_ID,
--     PRODUCT_ID,
--     REPLACE(
--         UPPER(CONTENT_TYPE),
--         'SOCIALMEDIA',
--         'SOCIAL MEDIA'
--     ) AS CONTENT_TYPE,
--     TRY_TO_NUMBER(
--         LEFT(
--             VIEWS_CLICKS,
--             CHARINDEX('-', VIEWS_CLICKS) - 1
--         )
--     ) AS VIEWS,
--     TRY_TO_NUMBER(
--         RIGHT(
--             VIEWS_CLICKS,
--             LEN(VIEWS_CLICKS) - CHARINDEX('-', VIEWS_CLICKS)
--         )
--     ) AS CLICKS,
--     LIKES,
--     ENGAGEMENT_DATE
-- FROM RAW_DATA.CUSTOMERS_ENGAGEMENT
-- WHERE UPPER(TRIM(CONTENT_TYPE)) <> 'NEWSLETTER';

-- CREATE OR REPLACE TASK CLEAN_DATA.ENGAGEMENT_TASK
-- WAREHOUSE = MARKETING_CAMP_WH
-- SCHEDULE = '1 MINUTE'
-- WHEN
-- SYSTEM$STREAM_HAS_DATA('RAW_DATA.CUSTOMER_ENGAGEMENT_STREAM')
-- AS
-- MERGE INTO CLEAN_DATA.CUSTOMERS_ENGAGEMENT AS TARGET 
-- USING
-- (SELECT ENGAGEMENT_ID, CONTENT_ID, CAMPAIGN_ID, PRODUCT_ID,
--         REPLACE( UPPER(CONTENT_TYPE), 'SOCIALMEDIA', 'SOCIAL MEDIA') AS CONTENT_TYPE,
--         TRY_TO_NUMBER(LEFT(VIEWS_CLICKS, CHARINDEX('-', VIEWS_CLICKS) - 1)) AS VIEWS,
--         TRY_TO_NUMBER(RIGHT(VIEWS_CLICKS,LEN(VIEWS_CLICKS) - CHARINDEX('-', VIEWS_CLICKS))) AS CLICKS,
--         LIKES, ENGAGEMENT_DATE
-- FROM RAW_DATA.CUSTOMER_ENGAGEMENT_STREAM
-- WHERE METADATA$ACTION = 'INSERT' AND UPPER(TRIM(CONTENT_TYPE)) <> 'NEWSLETTER'
-- ) AS SOURCE
-- ON TARGET.ENGAGEMENT_ID = SOURCE.ENGAGEMENT_ID
-- WHEN MATCHED THEN
--     UPDATE ALL BY NAME
-- WHEN NOT MATCHED THEN
--     INSERT ALL BY NAME;

SHOW TASKS IN SCHEMA CLEAN_DATA;
ALTER TASK CLEAN_DATA.ENGAGEMENT_TASK RESUME;

SELECT * FROM CLEAN_DATA.CUSTOMERS_ENGAGEMENT WHERE ENGAGEMENT_ID = 9999;

INSERT INTO RAW_DATA.CUSTOMERS_ENGAGEMENT
VALUES(9999, 48, 'video', 260, '2023-05-23', 17, 8, '1000-450');

SELECT * FROM RAW_DATA.CUSTOMER_ENGAGEMENT_STREAM;
-- EXECUTE TASK CLEAN_DATA.ENGAGEMENT_TASK;
