-- Marketing & Customer Behaviour Analytics
-- Snowflake database and schema setup
-- Production setup extracted from the complete working SQL.

CREATE WAREHOUSE MARKETING_CAMP_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE MARKETING_CAMP_ANALYSIS;

CREATE SCHEMA MARKETING_CAMP_ANALYSIS.RAW_DATA;
CREATE SCHEMA MARKETING_CAMP_ANALYSIS.CLEAN_DATA;

USE DATABASE MARKETING_CAMP_ANALYSIS;
USE SCHEMA RAW_DATA;
